export const AGREGA_CARRITO = "AGREGAR_CARRITO";
export const ELIMINAR_PRODUCTO_CARRITO = "  ELIMINAR_PRODUCTO_CARRITO";
export const  ELIMINAR_TODOS_PRODUCTO_CARRITO = "ELIMINAR_TODOS_PRODUCTO_CARRITO";
export const  LIMPIAR_CARRITO = "LIMPIAR_CARRITO";